kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-data
  namespace: formacion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2