apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: formacion
  labels:
    app: mongo
spec:
  ports:
    - name: 27017-tcp
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    deploymentconfig: mongo
  type: ClusterIP
